name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/hayhaylonton/samba4-ad:$GITHUB_SHA --tag ghcr.io/hayhaylonton/samba4-ad:latest

  push_image:
    needs: build
    runs-on: self-hosted
    steps:
    - name: push image to github registry
      run: |
        docker push ghcr.io/hayhaylonton/samba4-ad:$GITHUB_SHA
        docker push ghcr.io/hayhaylonton/samba4-ad:latest