name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  TAG_NAME=hello
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@
    - name: set TAG_NAME
      run: echo "TAG_NAME=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/hayhaylonton/samba4-ad:TAG_NAME --tag ghcr.io/hayhaylonton/samba4-ad:latest

  push image:

    runs-on: self-hosted

    steps:
    - name: push image to github registry
      run: |
        docker push ghcr.io/hayhaylonton/samba4-ad:TAG_NAME
        docker push ghcr.io/hayhaylonton/samba4-ad:latest